# meta developers: @Den4ikSuperOstryyPer4ik and @ToXicUse

from .. import loader
from asyncio import sleep 

class LikeAndTrollmod(loader.Module):
	"""Я покажу тебе, какой ты прекрасный человек
	(ну или плохой, пхпх)  :)"""
	strings = {"name": "Compliments and Toxicity"}
	async def likeZpmcmd(self, message):
		"""—>Комплиментики для девушки в лс"""
		await message.edit("Ты......")
		await sleep(1)
		await message.edit("Ты...прекрасная...")
		await sleep(1)
		await message.edit("Ты...прекрасная, а еще....")
		await sleep(0.5)
		await message.respond("красивая")
		await sleep(0.5)
		await message.respond("умная")
		await sleep(0.5)
		await message.respond("заботливая")
		await sleep(0.5)
		await message.respond("привлекательная")
		await sleep(0.5)
		await message.respond("добрая")
		await sleep(0.5)
		await message.respond("ахуенная")
		await sleep(0.5)
		await message.respond("нежная")
		await sleep(0.5)
		await message.respond("милая")
		await sleep(0.5)
		await message.respond("очаровательная")
		await sleep(0.5)
		await message.respond("неповторимая")
		await sleep(0.5)
		await message.respond("незабываемая")
		await sleep(0.5)
		await message.respond("шикарная")
		await sleep(0.5)
		await message.respond("божественная")
		await sleep(0.5)
		await message.respond("ангельская")
		await sleep(0.5)
		await message.respond("яркая")
		await sleep(0.5)
		await message.respond("крутая")
		await sleep(0.5)
		await message.respond("пушистая")
		await sleep(0.5)
		await message.respond("обалденная")
		await sleep(0.5)
		await message.respond("весёлая")
		await sleep(0.5)
		await message.respond('энергичная')
		await sleep(0.5)
		await message.respond('креативная')
		await sleep(0.5)
		await message.respond('разносторонняя')
		await sleep(0.5)
		await message.respond('сказочная')
		await sleep(0.5)
		await message.respond('симпатичная')
		await sleep(0.5)
		await message.respond('ласковая')
		await sleep(0.5)
		await message.respond('следенькая')
		await sleep(0.5)
		await message.respond('желанная')
		await sleep(0.5)
		await message.respond('загадочная')
		await sleep(0.5)
		await message.respond('цветущая')
		await sleep(0.5)
		await message.respond('безупречная')
		await sleep(0.5)
		await message.respond('отзывчивая')
		await sleep(0.5)
		await message.respond('лучшая')
		await sleep(0.5)
		await message.respond('скромная')
		await sleep(0.5)
		await message.respond('искренная')
		await sleep(0.5)
		await message.respond('дружелюбная')
		await sleep(0.5)
		await message.respond('понимающая')
		await sleep(0.5)
		await message.respond('мечтательная')
		await sleep(0.5)
		await message.respond('восторженная')
		await sleep(0.5)
		await message.respond("прелестная")
		await sleep(0.5)
		await message.respond("игривая")
		await sleep(0.5)
		await message.respond('офигительная')
		await sleep(0.5)
		await message.respond('изумительная')
		await sleep(0.5)
		await message.respond("трогательная")
		await sleep(0.5)
		await message.respond("В общем, зайка, ты самая ахуенная и самая-самая лучшая!)")
		
	async def likeZchatcmd(self, message):
		"""—>Комплиментики для девушек в чате(не лс)"""
		await message.edit("Каждая девушка/девочка/женщина в этом чате...")
		await sleep(1)
		await message.edit("Каждая девушка/девочка/женщина в этом чате прекрасная....")
		await sleep(1)
		await message.edit("Каждая девушка/девочка/женщина в этом чате прекрасна.... еще каждая из них:")
		await sleep(0.5)
		await message.respond("красивая")
		await sleep(0.5)
		await message.respond("умная")
		await sleep(0.5)
		await message.respond("заботливая")
		await sleep(0.5)
		await message.respond("привлекательная")
		await sleep(0.5)
		await message.respond("добрая")
		await sleep(0.5)
		await message.respond("ахуенная")
		await sleep(0.5)
		await message.respond("нежная")
		await sleep(0.5)
		await message.respond("милая")
		await sleep(0.5)
		await message.respond("очаровательная")
		await sleep(0.5)
		await message.respond("неповторимая")
		await sleep(0.5)
		await message.respond("незабываемая")
		await sleep(0.5)
		await message.respond("шикарная")
		await sleep(0.5)
		await message.respond("божественная")
		await sleep(0.5)
		await message.respond("ангельская")
		await sleep(0.5)
		await message.respond("яркая")
		await sleep(0.5)
		await message.respond("крутая")
		await sleep(0.5)
		await message.respond("пушистая")
		await sleep(0.5)
		await message.respond("обалденная")
		await sleep(0.5)
		await message.respond("весёлая")
		await sleep(0.5)
		await message.respond('энергичная')
		await sleep(0.5)
		await message.respond('креативная')
		await sleep(0.5)
		await message.respond('разносторонняя')
		await sleep(0.5)
		await message.respond('сказочная')
		await sleep(0.5)
		await message.respond('симпатичная')
		await sleep(0.5)
		await message.respond('ласковая')
		await sleep(0.5)
		await message.respond('следенькая')
		await sleep(0.5)
		await message.respond('желанная')
		await sleep(0.5)
		await message.respond('загадочная')
		await sleep(0.5)
		await message.respond('цветущая')
		await sleep(0.5)
		await message.respond('безупречная')
		await sleep(0.5)
		await message.respond('отзывчивая')
		await sleep(0.5)
		await message.respond('лучшая')
		await sleep(0.5)
		await message.respond('скромная')
		await sleep(0.5)
		await message.respond('искренная')
		await sleep(0.5)
		await message.respond('дружелюбная')
		await sleep(0.5)
		await message.respond('понимающая')
		await sleep(0.5)
		await message.respond('мечтательная')
		await sleep(0.5)
		await message.respond('восторженная')
		await sleep(0.5)
		await message.respond("прелестная")
		await sleep(0.5)
		await message.respond("игривая")
		await sleep(0.5)
		await message.respond('офигительная')
		await sleep(0.5)
		await message.respond('изумительная')
		await sleep(0.5)
		await message.respond("трогательная")
		await sleep(0.5)
		await message.respond('и так далее, зайки, простите, что тут не всё, просто не вмещается, а так вы прекрасны!)')
		

	async def loveanimationcmd(self, message):
		"""—>Анимация(очень быстрая) с комплиментами для любимой(beta)"""
		await message.edit("Команда на данный момент разрабатывается.")

	async def toxicpmcmd(self, message):
		"""—>Оскорбления для лс, токсичность на сотке"""
		await message.edit("Яя..")
		await sleep(1)
		await message.edit("Яя.. т")
		await sleep(1)
		await message.edit("Яя.. ток")
		await sleep(1)
		await message.edit("Яя.. токси")
		await sleep(1)
		await message.edit("Яя.. токсичн")
		await sleep(1)
		await message.edit("Яя.. токсичный")
		await sleep(1)
		await message.edit("Яя.. токсичный че...")
		await sleep(1)
		await message.edit("Яя.. токсичный чело...")
		await sleep(1)
		await message.edit("Яя.. токсичный человек...")
		await sleep(1)
		await message.edit("Яя.. токсичный человек \nА ты...")
		await sleep(0.4)
		await message.respond("Дебил")
		await sleep(0.3)
		await message.respond("Еблан")
		await sleep(0.3)
		await message.respond("Долбоеб")
		await sleep(0.3)
		await message.respond("Хуйло")
		await sleep(0.3)
		await message.respond("Чурка")
		await sleep(0.3)
		await message.respond("Гадой")
		await sleep(0.3)
		await message.respond("Нищий")
		await sleep(0.3)
		await message.respond("Ущемленный")
		await sleep(0.3)
		await message.respond("Приемыш")
		await sleep(0.3)
		await message.respond("Гандон")
		await sleep(0.3)
		await message.respond('Дурак')
		await sleep(0.3)
		await message.respond('Сволочь')
		await sleep(0.3)
		await message.respond('хуесосина')
		await sleep(0.3)
		await message.respond('пидрила')
		await sleep(0.3)
		await message.respond('сын шлюхи')
		await sleep(0.3)
		await message.respond('пиздятина')
		await sleep(0.3)
		await message.respond('гнида')
		await sleep(0.3)
		await message.respond('щенок мелкий')
		await sleep(0.3)
		await message.respond('школьник ебаный')
		await sleep(0.3)
		await message.respond('поебень')
		await sleep(0.3)
		await message.respond('пиздабол')
		await sleep(0.3)
		await message.respond('распиздяй')
		await sleep(0.3)
		await message.respond('подлец')
		await sleep(0.3)
		await message.respond('быдло')
		await sleep(0.3)
		await message.respond('подонок')
		await sleep(0.3)
		await message.respond('помнишь как я твою мать ебал с своими друзьями?')
		await sleep(0.3)
		await message.respond('хуеглот ебучий)')
		await sleep(0.3)
		await message.respond('сын путаны раздолья)')
		await sleep(0.3)
		await message.respond('подсос моего хуя)')
		await sleep(0.3)
		await message.respond('суда ползи спидозник)')
		await sleep(0.3)
		await message.respond('ты хули умолк хуй сосёшь не многоли чести')
		await sleep(0.3)
		await message.respond("хуйня из под ног?))")
		await sleep(0.3)
		await message.respond("помню помню, недавно тобой пол в параше протер) но уже можешь вылезать")
		await sleep(0.3)
		await message.respond("ты понимаешь что ты зонтик держишь когда я твою мать при ливне ебу?")
		await sleep(0.3)
		await message.respond("мой хуй выбил страйк зубами твоей матери")
		await sleep(0.3)
		await message.respond("пойми) я ща пиздак твоей матери расстяну так что он сможет надеть всю землю")
		await sleep(0.3)
		await message.respond("пойми) мой хуй ща будет ездить по твоей голове как газоно-косилка по траве")
		await sleep(0.3)
		await message.respond("давай запакуем твою мамашку и отправим по адресу прямо на мой хуй,кондуктор ебаный")
		await sleep(0.3)
		await message.respond("мой хуй твою мать вытирает своими яйцами, когда она моестся")
		await sleep(0.3)
		await message.respond("хуесос ты мартовский)")
		await sleep(0.3)
		await message.respond("шавка ты иди полы мой в рестаране)")
		await sleep(0.3)
		await message.respond("какой рестаран в чикен бекон иди мой)")
		await sleep(0.3)
		await message.respond("и принеси туда мамку чтобыо на под столом сосала!)")
		await sleep(0.3)
		await message.respond("педобир ахуевший?")
		await sleep(0.3)
		await message.respond("ты ща мою сперму есть будешь как кашку манную маленбкие дети,ты молокосос,а я тебя заставлю это сделать обрыганец чертов")
		await sleep(0.3)
		await message.respond('закрой свой рот хуила ебаная')
		await sleep(0.3)
		await message.respond('у меня еще дохуища оскорблений, просто жаль тебя. поэтому иди отдыхай, скоро снова сосать будешь')
		await sleep(0.3)
		await message.respond("дополнение: если у вас есть отличный список оскорблений, то прошу кидать в лс @Den4ikSuperOstryyPer4ik либо @ToXicUse, благодарю")
		
	async def ninemaycmd(self, message):
	   """—>Поздравление с 9 мая!:)"""
	   await message.edit("Ребятки, ")
	   await sleep(3)
	   await message.edit('Ребятки, поздравляю')
	   await sleep(3)
	   await message.edit('Ребятки, поздравляю вас')
	   await sleep(3)
	   await message.edit('Ребятки, поздравляю вас всех')
	   await sleep(3)
	   await message.edit('Ребятки, поздравляю вас всех с днём Победы!!!!')
	   await sleep(3)
	   await message.edit('Ребятки, поздравляю вас всех с днём Победы!!!! В этот великий праздник')
	   await sleep(3)
	   await message.edit('Ребятки, поздравляю вас всех с днём Победы!!!! В этот великий праздник хочется пожелать мирного неба над головой, ')
	   await sleep(3)
	   await message.edit('Ребятки, поздравляю вас всех с днём Победы!!!! В этот великий праздник хочется пожелать мирного неба над головой, пусть птицы поют громче, ')
	   await sleep(3)
	   await message.edit('Ребятки, поздравляю вас всех с днём Победы!!!! В этот великий праздник хочется пожелать мирного неба над головой, пусть птицы поют громче, солнце светит ярче, ')
	   await sleep(3)
	   await message.edit('Ребятки, поздравляю вас всех с днём Победы!!!! В этот великий праздник хочется пожелать мирного неба над головой, пусть птицы поют громче, солнце светит ярче, а радость и улыбки ')
	   await sleep(3)
	   await message.edit('Ребятки, поздравляю вас всех с днём Победы!!!! В этот великий праздник хочется пожелать мирного неба над головой, пусть птицы поют громче, солнце светит ярче, а радость и улыбки будут всегда на ваших лицах.')
	   await sleep(3)
	   await message.edit('Ребятки, поздравляю вас всех с днём Победы!!!! В этот великий праздник хочется пожелать мирного неба над головой, пусть птицы поют громче, солнце светит ярче, а радость и улыбки будут всегда на ваших лицах. Здоровья вам и вашим семьям, ')
	   await sleep(3)
	   await message.edit('Ребятки, поздравляю вас всех с днём Победы!!!! В этот великий праздник хочется пожелать мирного неба над головой, пусть птицы поют громче, солнце светит ярче, а радость и улыбки будут всегда на ваших лицах. Здоровья вам и вашим семьям, лёгкого преодоление всех трудностей, и просто всех жизненных благ! \nСтих вам: \nПоздравляю с Днём Победы ')
	   await sleep(3)
	   await message.edit('Ребятки, поздравляю вас всех с днём Победы!!!! В этот великий праздник хочется пожелать мирного неба над головой, пусть птицы поют громче, солнце светит ярче, а радость и улыбки будут всегда на ваших лицах. Здоровья вам и вашим семьям, лёгкого преодоление всех трудностей, и просто всех жизненных благ! \nСтих вам: \nПоздравляю с Днём Победы \nИ желаю в этот день')
	   await sleep(3)
	   await message.edit('Ребятки, поздравляю вас всех с днём Победы!!!! В этот великий праздник хочется пожелать мирного неба над головой, пусть птицы поют громче, солнце светит ярче, а радость и улыбки будут всегда на ваших лицах. Здоровья вам и вашим семьям, лёгкого преодоление всех трудностей, и просто всех жизненных благ! \nСтих вам: \nПоздравляю с Днём Победы \nИ желаю в этот день \nМоре радости и света, ')
	   await sleep(3)
	   await message.edit('Ребятки, поздравляю вас всех с днём Победы!!!! В этот великий праздник хочется пожелать мирного неба над головой, пусть птицы поют громче, солнце светит ярче, а радость и улыбки будут всегда на ваших лицах. Здоровья вам и вашим семьям, лёгкого преодоление всех трудностей, и просто всех жизненных благ! \nСтих вам: \nПоздравляю с Днём Победы \nИ желаю в этот день \nМоре радости и света, \nИ здоровья как кремень!')
	   await sleep(3)
	   await message.edit('Ребятки, поздравляю вас всех с днём Победы!!!! В этот великий праздник хочется пожелать мирного неба над головой, пусть птицы поют громче, солнце светит ярче, а радость и улыбки будут всегда на ваших лицах. Здоровья вам и вашим семьям, лёгкого преодоление всех трудностей, и просто всех жизненных благ! \nСтих вам: \nПоздравляю с Днём Победы \nИ желаю в этот день \nМоре радости и света, \nИ здоровья как кремень! \n. \nНе забыт великий праздник,')
	   await sleep(3)
	   await message.edit('Ребятки, поздравляю вас всех с днём Победы!!!! В этот великий праздник хочется пожелать мирного неба над головой, пусть птицы поют громче, солнце светит ярче, а радость и улыбки будут всегда на ваших лицах. Здоровья вам и вашим семьям, лёгкого преодоление всех трудностей, и просто всех жизненных благ! \nСтих вам: \nПоздравляю с Днём Победы \nИ желаю в этот день \nМоре радости и света, \nИ здоровья как кремень! \n. \nНе забыт великий праздник, \nХоть прошли уже года.')
	   await sleep(3)
	   await message.edit('Ребятки, поздравляю вас всех с днём Победы!!!! В этот великий праздник хочется пожелать мирного неба над головой, пусть птицы поют громче, солнце светит ярче, а радость и улыбки будут всегда на ваших лицах. Здоровья вам и вашим семьям, лёгкого преодоление всех трудностей, и просто всех жизненных благ! \nСтих вам: \nПоздравляю с Днём Победы \nИ желаю в этот день \nМоре радости и света, \nИ здоровья как кремень! \n. \nНе забыт великий праздник, \nХоть прошли уже года. \nЖелаю вам добра и счастья,')
	   await sleep(3)
	   await message.edit('Ребятки, поздравляю вас всех с днём Победы!!!! В этот великий праздник хочется пожелать мирного неба над головой, пусть птицы поют громче, солнце светит ярче, а радость и улыбки будут всегда на ваших лицах. Здоровья вам и вашим семьям, лёгкого преодоление всех трудностей, и просто всех жизненных благ! \nСтих вам: \nПоздравляю с Днём Победы \nИ желаю в этот день \nМоре радости и света, \nИ здоровья как кремень! \n. \nНе забыт великий праздник, \nХоть прошли уже года. \nЖелаю вам добра и счастья, \nНеба мирного всегда!! \nНу что ребята, С ПРАЗДНИКОМ ВАС!!!!')
	
